NeuraLegion/cypress-har-generator

- README.md
- example/cypress/plugins/index.js
- src/Plugin.ts
- src/index.ts
**BREAKING CHANGE**: `install` function has been split in two parts: `install` and `ensureRequiredBrowserFlags`.
Before:
```js
const { install } = require('@neuralegion/cypress-har-generator');
module.exports = (on, config) => {
install(on, config);
};
```
After:
```js
const { install, ensureRequiredBrowserFlags } = require('@neuralegion/cypress-har-generator');
module.exports = (on, config) => {
install(on, config);
on('before:browser:launch', (browser = {}, args) =>
ensureRequiredBrowserFlags(browser, args)
);
};
```
closes #13
> feat(plugin): allow the users to configure browser args

- src/Plugin.ts
having problem when use this with Zuora's HMAC protocol
https://www.zuora.com/developer/api-reference/#tag/HMAC-Signatures
I found if I delete that option, everything would still work. Curious why that was added to begin with.
> fix(security): remove disable-web-security due to issues with Zuora

- src/Plugin.ts
- src/commands.ts
According to the documentation of this library it implies that you can specify `fileName` and `outDir` independently of each other. However this type is written such that you need to specify both even when you may only want to override one. (ie: only `outDir` and not `fileName`).
I've made both of the properties on the SaveOptions type to be optional to solve this. If nothing is specified, then the default behavior occurs.
> make fileName and outDir optional on SaveOptions

- README.md
- src/Plugin.ts
- src/network/NetworkObserver.ts
These changes add a new attribute `excludePaths` to the available Record
Options.
Consumers may provide a set of pathnames which will be used
to filter network entries from the recorded HAR file.
> Allow user to filter pathnames from the recording

- src/network/NetworkRequest.ts
This fixes an issue where the plugin crashes if a request does not have a Content-Type header.
> fix(network): handle case where `requestContentType` is undefined

- README.md
- src/Plugin.ts
- src/network/NetworkObserver.ts
Extend recording options by adding `includeHosts` field to include only requests on specific hosts.
> feat(network): allow to filter hosts

- README.md
- src/Plugin.ts
- src/index.ts
The `ensureBrowserFlags` function has been deprecated. Use the `install` function instead as follows:
```diff
setupNodeEvents(on) {
install(on);
-
-  on('before:browser:launch', (browser = {}, launchOptions) => {
-    ensureBrowserFlags(browser, launchOptions);
-    return launchOptions;
-  });
}
```
In case of any issues please refer to Cypress-io/cypress#5240
closes #100
> fix(plugin): prevent NPE on writable stream

- src/network/NetworkObserver.ts
- src/network/NetworkRequest.ts
> fix(network): prevent duplicating a query string in `requestHeadersText`

- README.md
- src/network/NetworkObserver.spec.ts
- src/network/NetworkObserver.ts
- src/network/NetworkObserverOptions.ts
You can pass an array of MIME types for which to record requests:
```js
cy.recordHar({ includeMimes: ['application/json'] });
```
This will record only requests with a MIME type of `application/json`.
closes #85
> feat(network): allow to specify a filter by mime types

- README.md
- src/network/NetworkObserverOptions.ts
- src/network/filters/CompositeFilter.ts
- src/network/filters/StatusCodeFilter.spec.ts
- src/network/filters/StatusCodeFilter.ts
To exclude requests based on their status code, you can use the `minStatusCodeToInclude` field.
For example, to only include requests that have a status code of 400 or greater, you can pass the `minStatusCodeToInclude` option as follows:
```js
cy.recordHar({ minStatusCodeToInclude: 400 });
```
closes #65
> feat(network): allow to excluding requests based on their status

- README.md
- src/Plugin.spec.ts
- src/Plugin.ts
- src/commands.ts
- src/index.ts
- src/network/NetworkObserver.ts
To stop the ongoing recording of network requests and disposes of the recorded logs, which will be not saved to a HAR file, new `disposeOfHar` command has been introduced.
You may use this command if you have started recording network logs with `recordHar` command, but you decide to refuse to save the recorded logs to a HAR file. Here's an example of how you might use this command to dispose of the HAR:
```js
describe('my tests', () => {
before(() => {
// start recording
cy.recordHar();
});
after(() => {
// decide not to save the recorded logs
cy.disposeOfHar();
});
});
```
closes #103
> feat(plugin): allow to dispose of a HAR file

- README.md
- src/network/DefaultObserverFactory.ts
- src/network/NetworkObserverOptions.ts
- src/network/NetworkRequest.spec.ts
- src/network/NetworkRequest.ts
- src/network/filters/BlobFilter.spec.ts
- src/network/filters/BlobFilter.ts
- src/network/filters/CompositeFilter.ts
- src/network/filters/index.ts
By default, when you use `recordHar` command, it will include the blob requests in the recorded HAR file. However, those requests only make sense when they are used on the same page they were created. To exclude the blob requests from the recorded HAR file, set the `includeBlobs` to false as follows:
```js
cy.recordHar({ includeBlobs: false });
```
> ✴ As of version 6, this flag will be disabled by default.
closes #141
> feat(network): filter blob network requests out from the HAR file

- jest.config.js
See `isolatedModules` drawbacks/limitations:
* https://www.typescriptlang.org/tsconfig#isolatedModules
* https://kulshekhar.github.io/ts-jest/docs/getting-started/options/isolatedModules/
> build(jest): speed up tests execution

- README.md
- src/Plugin.spec.ts
- src/Plugin.ts
- src/network/NetworkIdleMonitor.spec.ts
- src/network/NetworkIdleMonitor.ts
- src/network/NetworkObserver.spec.ts
- src/network/NetworkObserver.ts
- src/network/Observer.ts
- src/network/index.ts
You can pass the `waitForIdle` option to wait for all pending requests to complete before saving the HAR file:
```js
cy.saveHar({ waitForIdle: true });
```
This option is false by default. When set to true, the plugin will monitor the count of pending requests and wait for it to reach zero before proceeding with saving the HAR file. This ensures that all responses have been received and the data in the file is complete and accurate.
closes #147
> feat(plugin):  wait for all requests before saving the HAR file

- README.md
- src/index.ts
If you're using Cypress version 6.2.0 or higher, you can set up hooks in a single step, eliminating the need to define them in each spec file. To do this, you need to call `enableExperimentalLifecycle` in addition to `install` as shown below:
```js
const { defineConfig } = require('cypress');
const {
install,
enableExperimentalLifecycle
} = require('@neuralegion/cypress-har-generator');
module.exports = defineConfig({
e2e: {
setupNodeEvents(on, config) {
install(on);
enableExperimentalLifecycle(on, config);
}
}
});
```
> Please note, to utilize this experimental mechanism for setting up lifecycle, you must either disable the interactive mode or enable the "experimentalInteractiveRunEvents" feature. For more details, see the documentation: …
> feat(plugin): provide a convenience mechanism to set up lifecycle

- README.md
- package.json
- src/Plugin.spec.ts
- src/Plugin.ts
To make the plugin work with Electron, you just need to set the `remote-debugging-port` option when you launch Cypress as follows:
```bash
$ ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port=9222 cypress run --browser electron
```
Please refer to the [Electron documentation](https://www.electronjs.org/docs/latest/api/command-line-switches#--remote-debugging-portport) and the [Cypress documentation](https://docs.cypress.io/api/plugins/browser-launch-api#Modify-Electron-app-switches) for more information on how to properly configure this switch.
closes #46
> feat(plugin): add support for Electron

- README.md
- cypress/e2e/record-har.cy.ts
- src/commands.ts
- src/network/NetworkObserverOptions.ts
- src/network/filters/HostFilter.spec.ts
- src/network/filters/HostFilter.ts
- src/network/filters/PathFilter.spec.ts
- src/network/filters/PathFilter.ts
- src/utils/StringUtils.spec.ts
- src/utils/StringUtils.ts
It is now possible to utilize regular expressions rather than strings when specifying the excludePaths or includeHosts options.
**Before**:
```ts
cy.recordHar({ excludePaths: ['^\\/api\\/products$', '^\\/api\\/users$'] });
```
**After**:
```ts
cy.recordHar({ excludePaths: [/^\/api\/products$/, '^\\/api\\/users$'] });
```
closes #163
> feat(plugin): accept the `RegExp | string` union type in the patterns

- README.md
- cypress/e2e/record-har.cy.ts
- cypress/fixtures/filter.cjs
- cypress/fixtures/filter.js
- cypress/fixtures/filter.mjs
- cypress/fixtures/filter.ts
- cypress/fixtures/transform.cjs
- cypress/fixtures/transform.js
- cypress/fixtures/transform.mjs
- cypress/fixtures/transform.ts
- src/Plugin.spec.ts
- src/Plugin.ts
- src/cdp/DefaultNetwork.ts
- src/index.ts
- src/network/DefaultHarExporter.spec.ts
- src/network/DefaultHarExporter.ts
- src/network/DefaultHarExporterFactory.spec.ts
- src/network/DefaultHarExporterFactory.ts
- src/network/DefaultHarExporterOptions.ts
- src/network/HarExporterFactory.ts
- src/network/index.ts
You can modify the entries before saving the HAR by using the `transform` option. This option should be set to a path to a module that exports a function, similar to the filter option, to change the Entry object as desired.
```js
cy.recordHar({ transform: '../support/remove-sensitive-data.ts' });
```
Here's a simple example of what the `remove-sensitive-data.ts` module might look like:
```ts
import { Entry } from 'har-format';
const PASSWORD_REGEXP = /("password":\s*")\w+("\s*)/;
export default async (entry: Entry) => {
try {
// Remove sensitive information from the request body
if (entry.request.postData?.text) {
entry.request.postData.text = entry.request.postData.text.replace(
PASSWORD_REGEXP,
'$1***$2'
);
}
return entry;
} catch {
return entry;
}
};
```
In this example, the transform …
> feat(plugin): allow to transform entries before saving a HAR

- README.md
- src/Plugin.ts
- src/constants.ts
- src/network/NetworkObserver.ts
- src/network/NetworkRequest.ts
You can pass the `waitForIdle` option to wait for all pending requests to complete before saving the HAR file:
```js
cy.saveHar({ waitForIdle: true });
```
This option is false by default. When set to true, the plugin will monitor the count of pending requests and wait for it to reach zero before proceeding with saving the HAR file. This ensures that all responses have been received and the data in the file is complete and accurate.
Additionally, you can pass the `maxWaitDuration` option to specify the maximum time to wait for the pending requests to complete:
```js
cy.saveHar({ waitForIdle: true, maxWaitDuration: 20000 });
```
The `maxWaitDuration` option is set to 5000 milliseconds by default, meaning it will wait for 5 seconds until all pending requests have completed.
You can also …
> feat(plugin): allow controlling the time to wait for idle network

- cypress/e2e/record-network-issues.cy.ts
> test: cover the case with the network error due to `cy.visit()`

- cypress/e2e/record-har.cy.ts
> test: cover the case with the headers attached at the proxy level

- cypress/app/index.ts
- cypress/app/views/post-data.hbs
- cypress/e2e/record-har.cy.ts
- src/cdp/DefaultNetwork.spec.ts
- src/cdp/DefaultNetwork.ts
- src/network/NetworkObserver.spec.ts
- src/network/NetworkObserver.ts
> fix(network): prevent sending redundant commands

- package-lock.json
- Bumped `get-func-name` to >= 2.0.1 to fix high-severity ReDoS vulnerability (GHSA-4q6p-r6v2-jvc5)
- Updated `micromatch` to >= 4.0.8 to resolve moderate-severity ReDoS vulnerability (GHSA-952p-6rrq-rcjv)
- Upgraded `path-to-regexp` to >= 0.1.10 to address high-severity backtracking issue (GHSA-9wv6-86v2-598j)
- Bumped `semver` to >= 5.7.2 to fix high-severity ReDoS vulnerability (GHSA-c2qf-rxjj-qqgw)
- Updated `ws` to a version >= 7.5.9 to mitigate high-severity DoS issue with HTTP headers (GHSA-3h5v-q93c-6h6q)
- 
Fixes applied via `npm audit fix`.
> fix(deps): bump package versions to resolve vulnerabilities

- src/Plugin.spec.ts
- src/Plugin.ts
Addresses https://github.com/NeuraLegion/cypress-har-generator/issues/5#issuecomment-1987030824
Previously the plugin would throw an error when it was running in an unsupported browser. This was not great for plugin consumers who run their cypress tests in both supported and unsupported browsers and are fine with only having HAR recording in supported browsers: It forced them to conditionally enable this plugin.
To address this, we're changing the plugin to do nothing except `warn` that HAR recording is not supported when running in an unsupported browser.
> feat(plugin): make plugin a "no-op" in unsupported browsers
