.github/workflows/deploy.yml
package-lock.json
package.json

chore: add npm token

---

package-lock.json
package.json

adds `tslib` in the list of dependencies and fixes several vulnerabilities wich could be updated automatically by `npm audit`
closes #8

fix(package.json): update list dependencies

---

example/cypress/support/index.js
support.js

fix(support): put in the root to allow using require with slash notation

---

README.md

I was confused just reading the docs where the archive.har file would be saved by default, I had to run the code to figure it out.

Add where default path to archive.har file will be saved

---

src/Plugin.ts
src/cdp/CRIConnection.ts
src/cdp/CRIOutputMessages.ts
src/network/NetworkObserver.ts
src/utils/Logger.ts

refactor(cdp): hide multiple logs of attempts to connect

---

src/Plugin.ts

fix(plugin): allow a user to set --headless via cypress

---

src/Plugin.ts
src/cdp/CRIConnection.ts
src/cdp/CRIOutputMessages.ts
src/cdp/index.ts
src/network/EntryBuilder.ts
src/network/ExtraInfoBuilder.ts
src/network/HarBuilder.ts
src/network/NetworkObserver.ts
src/network/NetworkRequest.ts
src/network/index.ts
typings/chrome-remote-interface/index.d.ts

#24 fix/websocket is not open

---

src/Plugin.ts
src/utils/FileManager.ts

refactor(utils): prevent leaking internal implementation details

---

src/Plugin.ts

fix(plugin): clear entries on `recordHar`

---

README.md

docs(readme): clarify usage of `outDir`

---

src/commands.ts

fix(commands): allow changing filename including its extension

---

src/Plugin.ts

fix(plugin): take into account both `--remote-debugging-address` and `--remote-debugging-port`

---

src/Plugin.ts

refactor(plugin): rename `ensureRdpPort` to `ensureRdpAddrArgs`

---

src/Plugin.ts
src/cdp/CRIConnection.ts
src/network/NetworkObserver.ts
src/utils/FileManager.ts

perf(plugin): prevent sudden growing of memory consumption

---

src/network/NetworkRequest.ts

fix(network): retrieving response cookies

---

src/network/NetworkRequest.ts

fix(network): parse content-type and filename from multipart/form-data

---

src/network/ExtraInfoBuilder.spec.ts
src/network/ExtraInfoBuilder.ts
src/network/NetworkObserver.spec.ts

fix(network): handle a request extra info coming before browser events

---

src/network/DefaultObserverFactory.ts
src/network/NetworkObserver.spec.ts
src/network/NetworkObserver.ts
src/network/filters/CompositeFilter.spec.ts
src/network/filters/CompositeFilter.ts
src/network/filters/HostFilter.spec.ts
src/network/filters/HostFilter.ts
src/network/filters/MimeFilter.spec.ts
src/network/filters/MimeFilter.ts
src/network/filters/PathFilter.spec.ts
src/network/filters/PathFilter.ts
src/network/filters/RequestFilter.ts
src/network/filters/index.ts

relates-to: #85
relates-to: #70
relates-to: #47

refactor(network): extract filter criteria to separate classes

---

.codeclimate.yml
cypress/app/index.ts
cypress/app/public/server-sent-events.js
cypress/app/public/websocket.js
cypress/app/views/server-sent-events.hbs
cypress/app/views/websocket.hbs
cypress/e2e/record-har.cy.ts
package-lock.json
package.json
src/network/EntryBuilder.spec.ts
src/network/EntryBuilder.ts
src/network/NetworkObserver.spec.ts
src/network/NetworkObserver.ts
src/network/NetworkRequest.spec.ts
src/network/NetworkRequest.ts

feat(network): allow to capture the server-sent events

---

src/network/EntryBuilder.spec.ts
src/network/EntryBuilder.ts

fix(network): remove square brackets from IPv6 address

---

src/Plugin.ts
src/cdp/CDPConnection.spec.ts
src/cdp/CDPConnection.ts
src/cdp/DefaultNetwork.spec.ts
src/cdp/DefaultNetwork.ts
src/cdp/messages.ts
src/constants.ts

fix(cdp): enhance error handling on the target attaching failure

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: improve the bug issue template

---

README.md

docs(readme): improve the usage example of `disposeOfHar`

---

src/network/DefaultHarExporter.ts

fix(network): typo in the log message

---

cypress/e2e/record-har.cy.ts
cypress/support/e2e.ts

test: cover the case when the request is issued by `cy.request()`

---

cypress/app/index.ts
cypress/app/views/post-data.hbs
cypress/e2e/record-har.cy.ts
src/cdp/DefaultNetwork.spec.ts
src/cdp/DefaultNetwork.ts

fix(cdp): call callback after session has been associated with request

---

src/cdp/DefaultNetwork.spec.ts
src/cdp/DefaultNetwork.ts
src/cdp/messages.ts

fix(cdp): avoid throwing errors for unknown session IDs

---

cypress/app/views/multi-targets.hbs
example/package-lock.json
example/package.json
package-lock.json
package.json

fixes #288
relates-to: cypress-io/cypress#26711

build(deps): bump cypress from 12.3.0 to 12.17.2
